### ISSUE TITLE
Reko fails to decompile m68000 code sample

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#122] opened 2016-01-29 08:11 UTC
Example code: [m68k_jump.zip](https://github.com/uxmal/reko/files/108123/m68k_jump.zip)
Now it has wrong decompilation result, and cannot be loaded without specifying AmigaOS base.

M68k family means m68000 too, and not only more or greater m68020.

Good decompilation result:

```
        movem.l d0-a6,-(sp)
        movea.l a0,a2
        movea.l a1,a6
        move.l  (a2)+,d0
        move.l  d0,(dword_FF0F08).l
        moveq   #0,d6
        move.l  d6,(dword_FF0F04).l
        movea.l d6,a4
        moveq   #$F,d2
        move.l  #$FF,d7
        bra.w   loc_C3DE
; ---------------------------------------------------------------------------

loc_C050:               ; CODE XREF: sub_C02A+3C0j
        move.l  a4,d3
        addq.l  #1,a4
        move.b  (a2,d3.l),d3
        and.l   d7,d3
        move.l  d3,d0
        andi.w  #$F0,d0 ; 'р'
        lsr.b   #2,d0
        cmpi.w  #$2C,d0 ; ','
        bgt.w   loc_C3DE
        movea.l off_C070(pc,d0.l),a5
        jmp (a5)
; ---------------------------------------------------------------------------
off_C070:   dc.l loc_C0A0
        dc.l loc_C0B6
        dc.l loc_C0D0
        dc.l loc_C0FA
        dc.l loc_C136
        dc.l loc_C16A
        dc.l loc_C1A0
        dc.l loc_C218
        dc.l loc_C22A
        dc.l loc_C23E
        dc.l loc_C27A
        dc.l loc_C2E0
```

**Comment by uxmal** [comment] 2016-01-29 08:31
When you say "wrong decompilation result", are you talking about the Reko disassembler window? It is "stupid" and will blindly disassemble data as code. What you want to look at is the asm file that reko generates (granted, it currently emits everything in Intel format -- that's another issue to deal with). Look at the .asm file that reko generates; it may look more sane.

**Comment by lab313ru** [comment] 2016-01-29 08:41
Yes, I mean the Reko disasm window, yes. Text in asm file looks the same.
First (compare with my result: *move.l  d0,(dword_FF0F08).l*):
```
 	move.l	d0,$97070F08
```
Then, offsets table for jumps. Reko is thinking, that they are just bytes.
```
Code vector at 00001046 (878 bytes)
00001046                   00 00 C0 A0 00 00 C0 B6 00 00       ..........
00001050 C0 D0 00 00 C0 FA 00 00 C1 36 00 00 C1 6A 00 00 .........6...j..
00001060 C1 A0 00 00 C2 18 00 00 C2 2A 00 00 C2 3E 00 00 .........*...>..
```

**Comment by uxmal** [comment] 2016-01-29 08:48
OK, the `move.l  d0,$97070F08` is a bug in the disassembler -- could you provide me with the bytes that correspond to the correct `move.l d0,(dword_FF0F08).l` instruction, and I will fix that.

I can also fix the asm file output to look nicer when reko knows there are pointer values. Rather than raw bytes in `Code vector` reko can dump appropriate assembler statements.

**Comment by lab313ru** [comment] 2016-01-29 08:50
```
23 C0 00 FF 0F 08
```

**Comment by uxmal** [comment] 2016-01-29 10:36
I just committed a few fixes. Look at `~/subjects/regressions/reko-121/m68k_jump.asm`. It starts like this:
```
fn0000C000()
	movem.l	d0-d7/a0-a6,-(a7)
	movea.l	a0,a2
	movea.l	a1,a6
	move.l	(a2)+,d0
	move.l	d0,$00FF0F08
	moveq	#$+00,d6
	move.l	d6,$00FF0F04
	movea.l	d6,a4
	moveq	#$+0F,d2
	move.l	#$000000FF,d7
	bra	$0000C3B4

l0000C026:
	move.l	a4,d3
	addq.l	#$01,a4
	move.b	(a2,d3),d3
	and.l	d7,d3
	move.l	d3,d0
	andi.w	#$00F0,d0
	lsr.b	#$02,d0
	cmpi.w	#$002C,d0
	bgt	$0000C3B4

l0000C040:
	movea.l	(04,pc,d0),a5
	jmp.l	(a5)
Code vector at 0000C046 (45 bytes)
	0000C0A0
	0000C0B6
	0000C0D0
	0000C0FA
	0000C136
	0000C16A
	0000C1A0
	0000C218
	0000C22A
	0000C23E
	0000C27A
```

Just to be sure: are you using "mark as procedure" in the memory view to help Reko determine where the start of the code is? Currently, when you give Reko a binary blob, it won't attempt to scan it unless the human tells it where executable code is, using "mark as procedure".

**Comment by lab313ru** [comment] 2016-01-29 10:45
Now, I'm using Open As... to open this binary. But it requires specifying AmigaOS, and doesn't work without specifying the OperatingEnvironment.

And, I really didn't know about "Mark as procedure" feature.

**Comment by lab313ru** [comment] 2016-01-29 10:49
Yep, I'm using it now!) Thank you.

**Comment by lab313ru** [comment] 2016-01-29 10:50
Hmm...
`Warning,00000046,The call or jump table has invalid addresses; stopping.`
`Warning,00000044,No valid entries could be found in jump vector.`

**Comment by uxmal** [comment] 2016-01-29 10:51
Can you give me the precise steps you are doing to get those warnings?

**Comment by lab313ru** [comment] 2016-01-29 10:55
1. Open As... 
1.1. m68k_jump.bin
1.2. AmigaOS
1.3. Motorola 68K family.

2. Scan binaries, analyze dataflow, reconstruct data types

3. Right mouse in Memory View, at the first byte (0x48), Mark procedure entry.

**Comment by uxmal** [comment] 2016-01-29 11:21
OK, it's not obvious what you should do here:
1. Open As...
    1.1 m68k_jump.bin
    1.2 AmigaOS
    1.3 Motorola 68k Family
2. In Memory View, `Mark Procedure Entry` at first byte.
3. Scan > Analyze > Reconstruct data types

On a tangent; would you like me to create a Sega Genesis platform? I'm guessing you're working on binaries for that machine, and it might be useful to have any OS services of that platform available for decompilation?

**Comment by lab313ru** [comment] 2016-01-29 11:27
Your order gives me that warnings too. It is strange.

Sega Genesis / Mega Drive uses M68000 as its main CPU.
Correct ROMs for it should contain 0x200 bytes of header: https://github.com/lab313ru/smd_ida_tools/blob/master/smd_loader/smd_loader.h
And the entry point is the `unsigned int Reset;` pointer. It would be great to support that.

But, it's not very hard to specify some offset as start address.

**Comment by uxmal** [comment] 2016-01-29 11:39
Is there a "magic number" like the "MZ" in MSDOS executables or the "\x7FELF" in ELF that could be used?

**Comment by uxmal** [comment] 2016-01-29 11:40
BTW: are you compiling Reko from the source tree or using the release 0.5.5.0 version?

**Comment by lab313ru** [comment] 2016-01-29 11:41
Nope. Nothing like that.

P.S. I think I'm getting these warnings, because I'm using Debug version? I'm compiling it from the source of `master` branch.

**Comment by uxmal** [comment] 2016-01-29 11:49
Shame about the lack of signature. However, I can create a "Sega Genesis" platform and that at least is a start.

**Comment by uxmal** [comment] 2016-01-29 11:50
As for the decompiler failure, I'm unable to reproduce it. I also built a Debug build, same result. What start address are you using? I'm using $C000.

**Comment by lab313ru** [comment] 2016-01-29 11:51
Oh... It is my fault, sorry. I'm using 0....
`However, I can create a "Sega Genesis" platform and that at least is a start.`
It will be great!

**Comment by lab313ru** [comment] 2016-01-29 11:53
`Warning,fn0000C000,Structure analysis stopped making progress, quitting. Please report this issue at https://github.com/uxmal/reko`
What that means?

**Comment by lab313ru** [comment] 2016-01-29 12:01
```
l0000C040:
	movea.l	(04,pc,d0),a5
	jmp.l	(a5)
Code vector at 0000C046 (45 bytes)
	0000C0A0
	0000C0B6
	0000C0D0
	0000C0FA
	0000C136
	0000C16A
	0000C1A0
	0000C218
	0000C22A
	0000C23E
	0000C27A
0000C046                   00 00 C0 A0 00 00 C0 B6 00 00       ..........
0000C050 C0 D0 00 00 C0 FA 00 00 C1 36 00 00 C1 6A 00 00 .........6...j..
0000C060 C1 A0 00 00 C2 18 00 00 C2 2A 00 00 C2 3E 00 00 .........*...>..
0000C070 C2 7A 00                                        .z.            
0000C073          00 C2 E0 C6 82 52 83 60 08 2C C6 58 B9    .....R.`.,.X.
0000C080 00 FF 0F 04 51 CB FF F6 60 00 03 2A C6 02 3C 3C ....Q...`..*..<<
0000C090 11 11 CC C3 36 06 48 46 3C 03 2C C6 58 B9 00 FF ....6.HF<.,.X...
```

**Comment by uxmal** [comment] 2016-01-29 12:08
That error is because a later stage, the part of Reko that makes `if`- `while`- and `switch` statements from your machine code is stuck in a loop and not making progress. You should open a separate issue to track that.I will open an issue to track SegaGenesis stuff.

Can we close this issue?

**Comment by lab313ru** [comment] 2016-01-29 12:09
`That error is because a later stage, the part of Reko that makes if- while- and switch statements from your machine code is stuck in a loop and not making progress.`
Could you create such issue? Because I don't understand what do you mean)

And yes, you can close this issue.

**Comment by lab313ru** [comment] 2016-01-29 12:25
Sorry, but this...)

Is it normal? Not all offsets are recognized (this offsets are absent):
```
ROM:0000C098                 dc.l loc_C27A
ROM:0000C09C                 dc.l loc_C2E0
```
Now code looks like that:
```
l0000C040:
	movea.l	(04,pc,d0),a5
	jmp.l	(a5)
Code vector at 0000C046 (45 bytes)
	0000C0A0
	0000C0B6
	0000C0D0
	0000C0FA
	0000C136
	0000C16A
	0000C1A0
	0000C218
	0000C22A
	0000C23E
	0000C27A
0000C046                   00 00 C0 A0 00 00 C0 B6 00 00       ..........
0000C050 C0 D0 00 00 C0 FA 00 00 C1 36 00 00 C1 6A 00 00 .........6...j..
0000C060 C1 A0 00 00 C2 18 00 00 C2 2A 00 00 C2 3E 00 00 .........*...>..
0000C070 C2 7A 00                                        .z.            
0000C073          00 C2 E0 C6 82 52 83 60 08 2C C6 58 B9    .....R.`.,.X.
0000C080 00 FF 0F 04 51 CB FF F6 60 00 03 2A C6 02 3C 3C ....Q...`..*..<<
0000C090 11 11 CC C3 36 06 48 46 3C 03 2C C6 58 B9 00 FF ....6.HF<.,.X...
```

**Comment by uxmal** [comment] 2016-01-29 12:30
Indeed, The limits are off. I will take a look at that this afternoon; need some fuel now <g>.

**Comment by lab313ru** [comment] 2016-01-29 12:46
0xC02A will be more correct offset to load the binary.

**Comment by uxmal** [comment] 2016-01-29 21:05
Commit 440e3240 fixes the memory view going blank when viewing address 0xC02A. You;ll notice that when using that address more of the binary decompiles correctly. I think I know how to get the last item in the jump vector but I'm saving that for tomorrow.

**Comment by uxmal** [comment] 2016-02-01 09:42
As reported by @lab313ru, Reko is now failing at type reconstruction time:

Error,,Error when reconstructing types. object reference not set to an instance of an object

**Comment by uxmal** [comment] 2016-02-01 09:44
Changed the title to more appropriately reflect the nature of the issue being tracked.

**Comment by uxmal** [comment] 2016-02-01 10:32
OK, now things get exciting. In the supplied program fragment Reko discovers that the value $00FF0F08 is being used as a pointer, so the `TypedConstantRewriter` wants to rewrite it as a pointer to a global variable. The problem is that the given image is based at $C02A, and ends at $C3F4. Therefore, $00FF0F08 is completely outside of the program image as known to Reko, and it makes the assumption that the out-of-range value is a sentinel value, like -1 or 0xFFFFFFFF often is.

The problem will also appear when decompiling any MS-DOS binary that does direct VGA accesses, where segment 0A000h is used to scribble pixels.

To resolve this, the user needs to be able to indicate to Reko that there is a valid memory area at $00FF0F08. That is, allow users to add **segments** to a Reko project. That is the topic of a separate issue #134.

@lab313ru : try now and see what happens.

**Comment by lab313ru** [comment] 2016-02-01 10:43
`try now and see what happens.`
It works, thank you!) So, now, waiting for ability to add custom memory regions..

**Comment by lab313ru** [comment] 2016-02-01 11:19
And jump tables too)

**Comment by uxmal** [comment] 2018-04-20 12:30
I think the items you're mentioned are covered in other issues.

**Closed by uxmal** 2018-04-20 12:30 UTC
