### ISSUE TITLE
MacOS Classic Analysis development, An internal error occurred. Offset must be non-negative. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#792] opened 2019-10-14 13:55 UTC
Sample program LinkIIgs
Error occurs during Analyze dataflow, 

Error,,An internal error occurred. Offset must be non-negative.
Parameter name: bitOffset

**Comment by uxmal** [comment] 2019-10-14 15:11
I'm unable to reproduce this; try this on commit a14dd9bfd487080a41926395c938b33baa759bea?

**Comment by gbody** [comment] 2019-10-27 12:36
The issue relates to the analysis-development branch, and has only occurred since the work you did that included fix(s) for  #785 MacOS Classic - analysis-development, sequence fusion performance - Feedback.

**Comment by gbody** [comment] 2019-10-27 13:02
I have compiled a clean/current copy of the analysis-development branch and I still get the same issue. I open sample file linkIIgs.hqx, then scan binaries, then Analyze dataflow. After the internal error occurs, the output from the debug window.
Prpr: Couldn't fuse assignments in reorder_LSegList
    v39_187 = SLICE(d6_184, word16, 16)
    v38_186 = SLICE(d6_184, word16, 0) + 0x0001
Prpr: Couldn't fuse assignments in change_Symbol
    v16_35 = SLICE(d7_32, word16, 16)
    v15_34 = SLICE(d7_32, word16, 0) << 0x0002
Prpr: Couldn't fuse assignments in change_Symbol
    v30_72 = SLICE(d0_65, word16, 16)
    v29_71 = Mem62[d0_65 + 12:word16]
Exception thrown: 'System.ArgumentOutOfRangeException' in Reko.Core.dll
The thread 0x16e8 has exited with code 0 (0x0).
The thread 0x1468 has exited with code 0 (0x0).

**Comment by uxmal** [comment] 2019-11-03 15:38
I'm able to reproduce this now. Investingating.

**Comment by uxmal** [comment] 2019-11-05 13:29
I've identified the problem and am working on a fix. Currently I'm seeing some big regressions in what looks like the macsbug symbol detection code; many of the labels have been switched around. If you like, I can push a development branch for my fix so you can take a peek.

**Comment by uxmal** [comment] 2019-11-07 00:59
Look at this to see if you can see the regressions I'm seeing.

**Comment by gbody** [comment] 2019-11-09 11:55
@uxmal are the regressions you are talking about like p2cstr appearing at address 001043a4 instead of 00104508. Is this the handling of PASCAL calling conventions issue #573 ,example the address range 001043A4 - 00104459 ending with jmpl (a?), being seen as a code block. Resulting in the block getting the name of the MACSBUG symbol from the later function.

**Comment by gbody** [comment] 2019-11-16 05:45
It appears to be fixed, with the previous error "An internal error occurred. Offset must be non-negative" , no longer occurring.

**Comment by gbody** [comment] 2019-11-24 14:10
@uxmal   Using Issue-792 branch
The Analyze dataflow now completes with either LinkIIgs.hqx or project file with procedure names defined. I haven't had a repeat of previous odd behaviour.
Now getting a build error for Issue-792 branch for cmdline and windows decompiler
Could not copy the file  "C:\GEOFF\projects\reko\src\Environments\Trs80\CoCoMemoryMap.xml" because it was not found.				

I also retried the Master branch again and it only failed if opening LinkIIgs.hqx, if using the project file with the defined names, it completed the Analyze dataflow ok.

**Comment by uxmal** [comment] 2020-01-19 23:00
I think we should be able to close this issue now. Do let me know if you see regressions.

**Closed by uxmal** 2020-01-19 23:00 UTC
Labels: bug
