### ISSUE TITLE
Finding main() function

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#212] opened 2016-04-22 10:38 UTC
Is it possible to add such feature? For example, I want to find main function in MS-DOS executables.

**Comment by uxmal** [comment] 2016-04-22 13:16
Could you provide more details what you mean here? Are you thinking about locating / skipping the C runtime boiler-plate code that gets linked into an executable, and try to find the actual user code that the CRT calls (the `main` function that the user wrote)? If so, this is a duplicate of #205. 

In order to accomplish this, I need a sample MS-DOS file where the problem is present. At the moment, I'm considering an ad-hoc method where first a match is made against a list of "templates" of CRT entry functions (from various compilers, programming languages, etc). Once a match is found, there will be a second template to identify the entry point into the actual binary.

**Comment by lab313ru** [comment] 2016-04-22 13:19
In @nemerle 's dcc there is a code for identifying entrypoints for MS-DOS executables, and for lib-functions too.

**Comment by nemerle** [comment] 2016-04-22 13:20
Yup the code just matches some very simple patterns  ( get's confused sometimes too) and calls it a day :smile:

**Comment by lab313ru** [comment] 2016-04-22 13:21
Such code could be used here to find WinMain or main() functions?

**Comment by uxmal** [comment] 2016-04-22 13:23
absolutely. Boomerang also does some really hacky work to find WinMain. I want a solution that involves as little code as possible, and as much pattern matching as possible. Reko already has a regexp engine that understands hexadecimal patterns. Now it's more about collecting such patterns. For that to happen, I need sample EXE files that have been built with a known compiler.

**Comment by nemerle** [comment] 2016-04-22 13:26
Nope, dcc 'main' locator patterns are dos only and pretty simplistic.
The ones that are a bit better are in [boomerang](https://github.com/nemerle/boomerang/blob/next/loader/exe/pe/Win32BinaryFile.cpp)

**Comment by uxmal** [comment] 2016-05-07 20:21
OK, the most recent checkins have added _general_ support for 'main' locator patterns. I've also grabbed some MS-DOS patterns from https://github.com/nemerle/dcc. Users still have to provide _specific_ 'main' patterns if Reko fails to find them. @lab313ru: If you have a binary that doesn't get its 'main' found, could you please forward it to me so I can locate the pattern and add it to Reko?

**Closed by uxmal** 2016-05-07 20:21 UTC

**Comment by lab313ru** [comment] 2016-05-13 08:18
How it marks **main()** function? Just "**fn...**"? If so, then at **PP219.EXE** it doesn't work. And it decompiles only one function at all (but it is not **main()** one).

**Comment by lab313ru** [comment] 2016-05-13 08:40
So what about Amiga executables?) But, there is no any info about pre-main stub anywhere.

**Comment by nemerle** [comment] 2016-05-13 09:04
Getting main detection to work on amiga executables would be a fun task for a binary archaeologist :smile: 

We'd need to have access to various amiga compiler ( Aztec C/ Lattice/ StormC/ others) libraries

**Comment by lab313ru** [comment] 2016-05-13 09:07
Some of them is possible to find at eab.abime.net forums, I hope.

**Comment by nemerle** [comment] 2016-05-13 09:18
Finding them will be the first step :)

The next one depends on the format of available data
* if we get the 'lib' files we'll need to cobble together a parser for those, and extract the ```start``` function pattern
* if we get 's' assembly sources, we'd need to convert it into byte patterns

**Comment by lab313ru** [comment] 2016-05-13 09:26
I'll try to find something. For example, for **PPAMI.EXE**.

**Comment by uxmal** [comment] 2016-05-13 12:41
@nemerle : those Amiga samples you provided to Reko (back when it was called "Decompiler") -- what compiler did you use for them?

**Comment by nemerle** [comment] 2016-05-13 16:07
It might have been the open source one - vbcc
