### ISSUE TITLE
Sega Genesis environment doesn't work in .msi version

### ISSUE THREAD

**Issue by Kalmalyzer** [uxmal/reko#528] opened 2018-01-02 20:12 UTC
Hi,

I noticed that Reko gives the following error messages if I install the pre-built version and attempt to open a Sega Genesis dump:

```
Unable to open memory map file 'SegaGenesis.xml. Could not open file 'C:\Program Files (x86)\jklSoft\Reko\SegaGenesis.xml'.
An internal error occurred. Object reference not set to an instance of an object.
```

The first bit is because SegaGenesis.xml is not part of Product.wxs. If I add the following line to Product.wxs, close to where Trs80Rom.xml is listed, then the error message changes:

```
        <File Source="$(var.SegaGenesis.ProjectDir)SegaGenesis.xml" />
```
... with that line in place, the new installer-package version will instead say:
```
Unable to open memory map file 'SegaGenesis.xml. Access to the path 'C:\Program Files (x86)\jklSoft\Reko\SegaGenesis.xml' is denied.
An internal error occurred. Object reference not set to an instance of an object.
```

If I take the entire Reko installation and move it outside of C:\Program Files (x86)  then it will no longer complain. I don't know about these Windows things, sounds like something involving app manifests or configs or ... eh?

Breakpointing in the code yields:

```
        public static MemoryMap_v1 LoadMemoryMapFromFile(IServiceProvider svc, string mmapFileName, IPlatform platform)
        {
            var cfgSvc = svc.RequireService<IConfigurationService>();
            var fsSvc = svc.RequireService<IFileSystemService>();
            var diagSvc = svc.RequireService<IDiagnosticsService>();
            try
            {
                var filePath = cfgSvc.GetInstallationRelativePath(mmapFileName);
                var ser = SerializedLibrary.CreateSerializer(
                    typeof(MemoryMap_v1),
                    SerializedLibrary.Namespace_v4);
                using (var stm = fsSvc.CreateFileStream(filePath, FileMode.Open)) <===== this throws an exception
                {
                    var mmap = (MemoryMap_v1)ser.Deserialize(stm);
                    return mmap;
                }
            }
            catch (Exception ex)
            {
                diagSvc.Error(ex, string.Format("Unable to open memory map file '{0}.", mmapFileName));
                return null;
            }
        }
```
Exception:
```
-		ex	{"Access to the path 'C:\\Program Files (x86)\\jklSoft\\Reko\\SegaGenesis.xml' is denied."}	System.Exception {System.UnauthorizedAccessException}
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2147024891	int
		HelpLink	null	string
+		InnerException	null	System.Exception
		Message	"Access to the path 'C:\\Program Files (x86)\\jklSoft\\Reko\\SegaGenesis.xml' is denied."	string
		Source	"mscorlib"	string
		StackTrace	"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode)\r\n   at Reko.Core.Services.FileSystemServiceImpl.CreateFileStream(String filename, FileMode mode)\r\n   at Reko.Core.Serialization.MemoryMap_v1.LoadMemoryMapFromFile(IServiceProvider svc, String mmapFileName, IPlatform platform)"	string
+		TargetSite	{Void WinIOError(Int32, System.String)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
+		Static members		
+		Non-Public members		
```

**Comment by Kalmalyzer** [comment] 2018-01-02 20:18
Hey wait, I think I got it. That CreateFileStream() call will open the file in read-write mode. It should be probably be replaced with:
```
                using (var stm = fsSvc.CreateFileStream(filePath, FileMode.Open, FileAccess.Read))
```

**Comment by Kalmalyzer** [comment] 2018-01-02 20:30
Ok, those two changes allow the XML file to be read. However, Reko.Environments.SegaGenesis.RomLoader.CreateSegmentMap() will fail because it expects a `.text` segment in the map, and that segment is commented out in the XML file (because that in turn caused some problem with the regression test suite).

**Comment by uxmal** [comment] 2018-01-02 20:35
Wow, what a complete bug report! Thanks for the investigation. Reading chapter and verse, the documentation for `FileStream`  specifies:

> You cannot use this constructor to open read-only files; instead, you must use a constructor that accepts a FileAccess parameter with the value set to FileAccess.Read.

As you noticed, making the change to add the `FileAccess.Read` flag makes the exception go away.

As for the `.text` issue, it's been a while since I looked at the memory map code. I can take a look tomorrow to see what's going on.

**Comment by Kalmalyzer** [comment] 2018-01-02 21:22
It's best to leave a live commentary here when I don't know how far I'll have time to take the debugging :)

To be extra clear: it makes sense for the `.text` section to be present in the memory map.

**Comment by uxmal** [comment] 2018-01-02 21:38
BTW: feel free to submit a PR for those two fixes you've made.

**Comment by uxmal** [comment] 2018-01-03 01:30
@Kalmalyzer : I added back the `.text.` section in the SEGA Genesis memory map and ran the regression tests. No errors found. Whatever problem there was in the regression tests must have disappeared a while ago. All we need is that PR from you and we can close this issue!

**Comment by uxmal** [comment] 2018-01-03 10:36
Looks like things are working better now. Thanks for reporting this issue and for your fixes.

**Closed by uxmal** 2018-01-03 10:36 UTC
