### ISSUE TITLE
To run this application, you must install .NET Core.

### ISSUE THREAD

**Issue by JustinsKittens** [uxmal/reko#1347] opened 2024-05-10 19:55 UTC
![image](https://github.com/uxmal/reko/assets/89991471/02dea837-18be-47f4-bcfb-823d50515253)
My OS is Windows 11, x64.
I click Yes, and nothing happens.

On the README, it says to use .NET 6. So, I go to the link it mentions, and it takes me to the .NET v8 download. I installed .NET v8 and tried again, same error. I then installed v6 and tried again, and the same error. I then read past issues, and came across an old one that the answer was to install .NET Core v5, so I installed v5 and the same error again.

I'm aware that sometimes, when you install a dependency for an application, you have to restart your system for the effects to fully take place. However, the installers and Decompiler say nothing about having to reboot my PC.

So, my question is: Do I have to reboot my PC after installing .NET? If not, then can you please provide help and/or insight as to why this error could be occurring repeatedly?

**Comment by uxmal** [comment] 2024-05-10 20:30
Thanks for reporting this. It is a stubborn issue which I unfortunately cannot reproduce on my machine. My suspicion is that Reko may be overly sensitive to the exact version of the .NET runtime you've install. When you installed .NET 6, which exact version was installed? Also, you shouldn't have to reboot your machine.

Another possibility is to install the .NET 6 SDK, but it shouldn't be necessary for only the runtime.

**Comment by JustinsKittens** [comment] 2024-05-10 20:35
Well, the thing is, I've installed both the SDK and the Runtime for all 3 versions.
My .NET 6 versions are:

SDK 6.0.421
ASP.NET Core Runtime 6.0.29
![image](https://github.com/uxmal/reko/assets/89991471/d9979511-f5c3-40b3-b3f8-d1e26fc98bac)

**Comment by uxmal** [comment] 2024-05-10 20:36
Thanks for the additional info. And how are you installing Reko? From the MSI installer or building it yourself?

**Comment by JustinsKittens** [comment] 2024-05-10 20:36
The MSI installer

**Comment by JustinsKittens** [comment] 2024-05-10 20:37
And, the exact versions were the most recent version listed on the download page for .NET 6, in case that info is needed

**Comment by uxmal** [comment] 2024-05-10 20:40
Where did you download Reko from? Sourceforge or github?

**Comment by JustinsKittens** [comment] 2024-05-10 20:43
Sourceforge. The latest installer was version 0.10.0. Which, now that I see the latest GitHub version was 0.11.5, the issue may be because of an outdated application. Should I try installing version 0.11.5?

**Comment by uxmal** [comment] 2024-05-10 20:44
Yes, I just uploaded 0.11.5 on Sourceforge as well. Try it and let me know how it goes.

**Comment by JustinsKittens** [comment] 2024-05-10 21:30
Yes, it now indeed works. Thank you very much

**Comment by uxmal** [comment] 2024-05-10 21:36
Thanks again for reporting this. I have a better understanding of what caused the problem. Closing now as resolved.

**Closed by uxmal** 2024-05-10 21:36 UTC
