### ISSUE TITLE
Adding PalmOS 68k Support

### ISSUE THREAD

**Issue by pinchies** [uxmal/reko#1301] opened 2023-12-03 14:22 UTC
As discussed on discord, I would be interested in learning what would be required to add full support for decompiling PalmOS .PRC executables, which are "mostly" 68K, and with a similar kind of [system call Trap API as on MacOS](https://github.com/uxmal/reko/issues/1033).

**Comment by uxmal** [comment] 2023-12-05 14:51
Simple PalmOS support is there. I'm closing this as completed, with the understanding that more features can be added.

**Closed by uxmal** 2023-12-05 14:51 UTC
Labels: enhancement

**Comment by uxmal** [comment] 2023-12-06 16:57
1. The Debug symbols look similar or maybe even identical with how Macsbug symbols are implemented on MacOS Classic. It might make sense to port that over to PalmOS. Look for `MacsBugSymbolScanner.cs` in the MacOS classic folder. If the symbols are indeed formatted the same, it might make sense to actually use the same class. The problem is that I don't want to add a dependency on MacOS in the PalmOS project, or vice versa, and these bits don't really belong in the M68k project. Perhaps I need to add a new `src/Libraries/MacsBug/MacsBug.csproj` to host this common code.
2. To find missing procedures, you can use Reko's shingle scanner. Once you load the program image into the Reko Gui, but before you've started the decompilation process, you can ask Reko to perform "Shingle scanning", which looks inside the "gaps" to see if it can make sense of them as code. To turn on this optional feature, you can select the executable in the Project Browser, Go to the `Edit > Properties` menu and bring up the property pages for the executable:
![image](https://github.com/uxmal/reko/assets/10154465/3291c170-c0b2-4439-9cbf-64f680832bf0)
If you then start the decompilation, you will collect more procedures.

**Comment by pinchies** [comment] 2023-12-06 22:27
Super, thanks for those details. Leave it with me and I’ll have a play! 🙌

**Comment by 999pingGG** [comment] 2024-04-11 18:57
How can I make it decompile all the "code" resources/segments? I needed, I can modify the code but I don't know where to look

![image](https://github.com/uxmal/reko/assets/56411048/e92d5967-bd4a-4bec-8159-098a5cdddf63)
