### ISSUE TITLE
OutOfMemoryException when decompiling m68k ROM

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#288] opened 2016-08-07 06:54 UTC
[tf3.zip](https://github.com/uxmal/reko/files/405344/tf3.zip)
I have 8 GB of memory, so...

**Comment by uxmal** [comment] 2016-08-07 07:33
That should not happen,  agreed  :)

**Comment by uxmal** [comment] 2016-08-07 07:59
I've reproduced this on my machine. Reko is going off the rails in `TrashedRegisterFinder`.

**Comment by uxmal** [comment] 2016-08-07 09:14
A contributing reason is that Reko has stared decompiling data as code. Since Reko is a conservative tracer, this means that some of the prior exceptions (due to unimplemented m68k opcodes) are causing it to fail. I will fix those exceptions first, to see whether the data-decompilation error goes away.

**Comment by uxmal** [comment] 2016-08-07 16:24
The OOM error is gone now. However, there are lots of exciting errors happening here, as is common for hand-written assembler. Especially challenging all all the `bsr $﻿4C84` calls, as each such call instruction is followed inline by a string to be written! This wonky kind of parameter passing was very popular in handwritten assembler (I recall it from my PDP-11 days), but very uncommon today. That's a topic for a separate issue. How to handle it in a general way is quite difficult, but with user help, perhaps the following string could be marked as "ignored" so that Reko can proceed.

**Closed by uxmal** 2016-08-07 16:24 UTC
Labels: bug
