### ISSUE TITLE
User defined stack arguments names do not appear in decompiled code

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#98] opened 2016-01-08 10:58 UTC
User defined stack arguments names do not appear in decompiled code. Names like "Arg04' are outputed instead. I have created unit test to demonstrate this (see b77c251)

I have solution (86beff8) and can do pull request but have some doubt
First, about return address. I use pointer size for it, maybe frame.ReturnAddressSize should be used
but it is not set on this stage.
Second, about duplicated ids, but when procSer.CreateId removing some unit tests failed

As for unit test, exception will be thrown if FakeArchitecture and FakePlatform will be used. So I used Win32Platform and IntelArchitecture. Maybe this should be modified too

**Comment by uxmal** [comment] 2016-01-08 11:30
I see where you're going with the proposed fix, but it's happening too soon in the decompilation process, before we know what the size of the return address is. The introduction of the names should happen in the scanner, when we known what the return address size is.

It clearly works for the regression test `switch.dcproj`. The output is here: [switch.c](../tree/master/subjects/regressions/snowman-51/switch.c). However, this is using the "old" `DataFlowAnalysis` class, and you've used the new `DataFlowAnalysis2` class which isn't quite yet in "production".  Let me look at this to see why the names are not being picked up.

**Comment by uxmal** [comment] 2016-01-08 11:52
I've found the cause and I'm working on a fix.

**Comment by ptomin** [comment] 2016-01-08 12:28
I have looked at switch.dcproj and found that it used "CSignature" tag to define signature.
My sample used "signature" tag. I have modified switch.dcproj to use "signature" instead of "CSignature" and reproduce case. I have attached this example
[switch.dcproject.txt](https://github.com/uxmal/reko/files/82669/switch.dcproject.txt)

**Comment by uxmal** [comment] 2016-01-08 12:29
Using a C-style signature is "preferred" over the serialized signatures. I will add support for that after the fix referred to above.

**Comment by ptomin** [comment] 2016-01-08 12:39
"referred to above"
You mean problem reproduced by unit test b77c251? But this is the same with one in "signature" version of switch.dcproject. Initially I catch this problem with "signature" version project file and then create unit test to demonstrate it

**Comment by uxmal** [comment] 2016-01-08 12:44
What I'm trying to say is: 
1. if you supply a C signature, like `void foo(int a, float b)`, and use the old `DataFlowAnalysis`, all is well. 
2. if you use C signature but use the new `DataFlowAnalysis2`, you will get unwanted results. `DataFlowAnalysis2` doesn't understand C signatures yet, that's the fix I'm working on now.
3. if you use `SerializedSignature_v1` with the new `DataFlowAnalysis2` you will also get unwanted results, for a different reason. I will fix that after I fix 2. above.

I'll try to get this out as soon as I can.

**Comment by ptomin** [comment] 2016-01-08 12:51
OK, now it is clear for me

**Comment by uxmal** [comment] 2016-01-08 13:02
I've now fixed 2. above. Before I start on 3. can you please explain why you are preferring to provide the user signatures as `SerializedSignature_v1` rather than the (arguably) more convenient C signatures `char * foo(int bar)`? I'm curious where you are going with this, and wish to assist if I can.

**Comment by ptomin** [comment] 2016-01-08 13:28
I have created project file by hand. I used SerializedSignature_v1 by analogy with windows32.xml.
I did not know about possibility to use C signatures. Yes, it is more convenient and there is no more reason for me for further using SerializedSignature_v1 in project files. You can drop support for it if you want

**Comment by uxmal** [comment] 2016-01-08 13:38
Good, I will close this now then.

**Closed by uxmal** 2016-01-08 13:38 UTC
