### ISSUE TITLE
Regression: Failure has occurred while loading a type

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#664] opened 2018-07-05 21:00 UTC
There are multiple subjects where a function has no body in 0.8.0.0 anymore compared to 0.7.x:

* https://github.com/rfalke/decompiler-subjects/blob/master/from_aminet/albion_demo/demo/m68k_amiga/by_reko.c: fn0000136C
* https://github.com/rfalke/decompiler-subjects/blob/master/from_boomerang/banner/ppc_elf_by_boomerang_o4/by_reko.c: main
* https://github.com/rfalke/decompiler-subjects/blob/master/from_boomerang/branch/ia32_elf_by_boomerang_sunos/by_reko.c: fde_insert
* https://github.com/rfalke/decompiler-subjects/blob/master/from_boomerang/true/ia32_elf_from_suse/by_reko.c: main
* https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/condition_eval_order/ia32_elf/by_reko.c: test_2_blocks

**Comment by uxmal** [comment] 2018-07-05 21:49
This is likely caused by exceptions being thrown during the decompilation. Alas I'm on vacation and have limited time to look at this closer until August.

**Comment by rfalke** [comment] 2018-07-06 06:05
I missed looking at the exceptions.

All cases are caused by 

```
Failure has occurred while loading a type.
      at Reko.Structure.StructureAnalysis.ProcessUnresolvedRegions () <0x40ad2420 + 0x00073> in <filename unknown>:0 
  at Reko.Structure.StructureAnalysis.Execute () <0x40acab60 + 0x00443> in <filename unknown>:0 
  at Reko.Structure.StructureAnalysis.Structure () <0x40ac96f0 + 0x00137> in <filename unknown>:0 
  at Reko.DecompilerDriver.StructureProgram () <0x40ac9210 + 0x00255> in <filename unknown>:0 
```
Maybe reko can show the information that an error occurred in the output? Something like:

```
int foo() {
  // exception Failure has occurred while loading a type.
}
```
or

```
// exception for foo: Failure has occurred while loading a type.
```

Anyway, have a nice holiday.

**Comment by uxmal** [comment] 2018-07-07 10:33
Hm, this is a little more exciting than I thought. The Mono runtime seems to be unable to load a CLR Type. I will try to reproduce this on my Linux VM when I get back.

**Comment by uxmal** [comment] 2018-07-13 15:54
Looks like this error went away once you started building your own reko binaries. I'm closing this for now, but if you see it again, please reopen.

**Closed by uxmal** 2018-07-13 15:54 UTC
