### ISSUE TITLE
Real-mode MSDOS code - switch reconstruction ?

### ISSUE THREAD

**Issue by nemerle** [uxmal/reko#25] opened 2015-08-19 19:43 UTC
While trying out reko on one of dcc's test files (BENCHFN.EXE) I've encountered a known problem with BuildMapping.

Namely, trying to reconstruct a 'switch', the engine tries to lookup the index table contents from the expression:

``` asm
mov     bl, BYTE PTR[bx+0x4F9]
```

Now in 16bit mode the 0x4F9 is actually the data segment relative address of the index table -(ds:0x4F9).
Shouldn't 0x4F9 be disassembled/interpreted as a (ds<<4 + 0x4F9) expression, and only if segment value is 'known' i.e.
- proven to be constant on all paths reaching the given instruction
- provided by the user at the instruction/block/function level

it can then be converted into a proper Address instance ?

**Comment by uxmal** [comment] 2015-08-19 20:41
Indeed, you have to prove that DS is constant before you can change the instruction from `Mem[ds:bx + 0x04F9]` to `Mem[(ds_04F9) + bx]`. The Scanner uses the `ProcedureState` class to keep a track of what registers are constant on entry to functions (a weak version of Value Set Analysis (VSA) that I implemented before I knew what VSA was). If `ProcedureState[ds]` is a constant (i.e. not invalid), then that fact should be taken advantage of. 

Note that if the instruction had been `mov bl,[cs:bx + 0x4F9]`, reko's scanner should do the right thing, since CS is obviously known.

If reko can't prove that DS is known, it can't resolve the switch. It wouldn't be very hard to add a dictionary, called `AssumeRegisterValues` or something, to the `UserProcedure` class. Users could add the key-value pair "DS = 0x1234" here. Then, when the scanner scans the procedure containing the switch statement, it would consult the `KnownRegisterValues` and override anything in the `ProcedureState`. Here we are using the user as an oracle; obviously if the user is mistaken, then reko will be led astray.

Would you like me to add this `AssumeRegisterValues` capability, given the lack of a full-blown VSA at the moment? It's more expedient, and kind of hacky, but it could prove to be quite useful. One could add 'AssumeRegisterValues` at any instruction address, of course.

**Comment by uxmal** [comment] 2015-08-20 20:22
I went ahead and implemented this feature for procedures. To set the assumed register values of a procedure, right-click on it in the project browser and select "Register values..." These will be saved in the project file.

**Comment by nemerle** [comment] 2015-08-21 09:23
Great :smile: 

I'll test it out as soon as I'm able and report back here

**Comment by uxmal** [comment] 2015-08-21 11:15
To allow setting the assumed register values on an instruction by instruction basis, we need to implement #30. But the data segment doesn't change often so you should be OK.

**Comment by xor2003** [comment] 2016-07-30 21:03
1. I'm converting IDA Pro .idc script. Can you implement "the assumed register values on an instruction by instruction basis" inside project xml file? So we will not need to wait for #30.
2. Maybe I'm doing something wrong: I defined global variables. I can see their names and sizes. I assumed ds for one function. But C output still contain Mem[SEGMENTREGISTER:OFFSET].

**Comment by uxmal** [comment] 2016-07-31 06:37
1. I can look into this on Tuesday when I will have access to a computer again.
2. If a Reko pass fails, due to exceptions, it will cause some or all segmented accesses to remain untranslated. Are you seeing any errors when you decompile your binary?

**Comment by xor2003** [comment] 2016-07-31 08:44
Thanks.
Yes, there are errors. It might be reason.
(no address or decompailer source file/line so cannot understand the root cause):
Warning,0800:24E6,Procedure sub_1279A previously had a return address of 0 bytes on the stack, but now seems to have a return address of 2 bytes on the stack.
Warning,0800:7551,Procedure setmemalloc2 previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0800:754F,Procedure setmemalloc1 previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Error,,An internal error occurred. Haven't handled this case yet. 
Error,,Error when reconstructing types. Not implemented: edx_eax_13 % edi_21

**Comment by uxmal** [comment] 2016-07-31 08:50
It's the last two errors that cause subissue 2 above. Is there any chance you could provide me with the binary?  If not, could you dump the assembler around the affected areas so I can take a look?

**Comment by xor2003** [comment] 2016-07-31 08:56
binary is here [https://cloud.mail.ru/public/2r7E/vja27S4je](https://cloud.mail.ru/public/2r7E/vja27S4je)

**Comment by xor2003** [comment] 2016-08-02 07:38
I can see also not all functions are decompiled. It is because of errors? So errors are critical and decompilation is not possible?

**Comment by uxmal** [comment] 2016-08-02 08:06
If reko is missing functions, it's because it cannot prove that those functions are reached. It's unlikely that directly called functions (e.g `call 0123:1235`) will not be decompiled. However, indirectly called functions are easily missed (e.g. `call far ptr es:[bx+0x10]`). In such cases, reko lets you (the user) specifically mark a location as being the start of a procedure, using the `Mark as Procedure` menu item, in the memory viewer.

**Comment by xor2003** [comment] 2016-08-02 10:06
1. This helps. And the function is decoded. But when I do save+close+reopen the project looks like this Procedure mark is not stored to project file.
2. Do I really need manually specify the Procedure entry point? Because I already added all procedure names and address in the project file. Maybe decompiler should reuse this info?
       <procedure name="moduleread">
        <characteristics />
        <address>0800:0000</address>
      </procedure>

**Comment by uxmal** [comment] 2016-08-02 11:02
Shall we move this over to https://gitter.im/uxmal/reko ? I'd be willing to help out troubleshooting, but I don't want to spam this issue entry, which is about assumed register values (I'm working on that right now btw)

**Comment by uxmal** [comment] 2016-08-02 12:00
@xor2003: commit 5f15a4c on the branch `user-register-statements` allows you to specify register values at any address of the program. You will have to edit the dcproj file directly until there is a user interface for it. To specify register values, add the following to the dcproj file:
```xml
<project>
  <input>
    <!-- stuff elided for clarity -->
    <user>
      <registerValues>
        <assume addr="0C00:0234" reg="ds" value="0D0A" />
      </registerValues>
    </user>
  </input>
</project>
```
Reko implements this by injecting the following statement "before" the actual instruction at `0C00:0234`:
```
ds = 0x0D0A
```
Please let me know how this works for you, and if you have any other ideas or suggestions for this feature.

**Comment by xor2003** [comment] 2016-08-02 12:35
Thank you. It should be. I will try to test it. I need to build the branch, right? Cannot guaranty it will be soon

**Comment by uxmal** [comment] 2016-08-02 14:58
I've merged the changes into the master branch; you won't need to build the branch. Give me a holler if you need help building and such.

**Closed** 2018-01-28 19:55 UTC
Labels: question
