### ISSUE TITLE
Unnecessary comparison written in recent builds

### ISSUE THREAD

**Issue by Allofich** [uxmal/reko#568] opened 2018-02-04 13:49 UTC
Hi, I've been testing Reko out on a program (an old MS-DOS game written in assembly) and recently the C output added an unnecessary comparison in a function.

Testing with the installations provided in the AppVeyor artifacts, the problem begins from commit d72c8a33 on Jan 16 this year.

Before then, it wrote this line:
`if (al_18 <u 0x30 || al_18 >u 0x39)`
Since then, it writes this line:
`if (al_18 <u 0x30 || (al_18 >u 0x39 || al_18 <u 0x30))`
It's redundant, right?

Here is the whole function as disassembled by Reko:

```;; fn0800_5298: 0800:5298
fn0800_5298 proc
	xor	dx,dx
	xor	cx,cx
	xor	ah,ah
	cmp	byte ptr [si],2D
	jnz	52A7

l0800_52A3:
	inc	si
	dec	cx
	jmp	52AD

l0800_52A7:
	cmp	byte ptr [si],2B
	jnz	52AD

l0800_52AC:
	inc	si

l0800_52AD:
	lodsb
	cmp	al,00
	jz	52C7

l0800_52B2:
	sub	al,30
	jc	52C7

l0800_52B6:
	cmp	al,09
	ja	52C7

l0800_52BA:
	add	dx,dx
	mov	bx,dx
	shl	dx,02
	add	dx,bx
	add	dx,ax
	jmp	52AD

l0800_52C7:
	and	cx,cx
	jns	52CD

l0800_52CB:
	neg	dx

l0800_52CD:
	mov	ax,dx
	ret
```

Here is the function rewritten by Reko into C

```// 0800:5298: Register word16 fn0800_5298(Register byte al, Register word16 si, Register selector ds, Register out ptr16 cxOut, Register out ptr16 dxOut)
word16 fn0800_5298(byte al, word16 si, selector ds, ptr16 & cxOut, ptr16 & dxOut)
{
	word16 dx_17;
	*dxOut = 0x00;
	word16 cx_12 = 0x00;
	if (Mem0[ds:si + 0x00:byte] == 0x2D)
	{
		si = si + 0x01;
		cx_12 = ~0x00;
	}
	else if (Mem0[ds:si + 0x00:byte] == 0x2B)
		si = si + 0x01;
	while (true)
	{
		byte al_18 = Mem0[ds:si + 0x00:byte];
		si = si + 0x01;
		if (al_18 == 0x00)
			break;
		ax = DPB(ax, al_18 - 0x30, 0);
		if (al_18 <u 0x30 || (al_18 >u 0x39 || al_18 <u 0x30))
			break;
		*dxOut = dx_17 * 0x02 * 0x05 + ax;
	}
	word16 cx_27;
	*cxOut = cx_12;
	if (cx_12 < 0x00)
		*dxOut = -dx_17;
	return dx_17;
}
```

**Comment by uxmal** [comment] 2018-02-04 16:54
Hello, and thanks for taking the effort to narrow this down -- that helps a lot! I will try to look at this regression the coming days. It clearly is redundant code being generated.

**Comment by Allofich** [comment] 2018-02-04 17:02
I used the installation from the AppVeyor artifacts, so it could be any of the commits between d72c8a3 and the last commit that had AppVeyor artifacts, 5d1e40de, which did not have the problem.

**Comment by Allofich** [comment] 2018-04-21 13:29
Since the other bug I reported https://github.com/uxmal/reko/issues/569 seems to be fixed, I tried this one as well, but the unnecessary comparison is still made. The disassembly is the same as above. The .c file output has changed slightly to the following:

```
// 0800:5298: Register word16 fn0800_5298(Register byte al, Register word16 si, Register selector ds, Register out ptr16 cxOut, Register out ptr16 dxOut, Register out ptr16 bxOut, Register out ptr16 siOut)
word16 fn0800_5298(byte al, word16 si, selector ds, ptr16 & cxOut, ptr16 & dxOut, ptr16 & bxOut, ptr16 & siOut)
{
	*bxOut = bx;
	word16 dx_17;
	*dxOut = 0x00;
	word16 cx_12 = 0x00;
	if (Mem0[ds:si + 0x00:byte] == 0x2D)
	{
		si = si + 0x01;
		cx_12 = ~0x00;
	}
	else if (Mem0[ds:si + 0x00:byte] == 0x2B)
		si = si + 0x01;
	while (true)
	{
		byte al_18 = Mem0[ds:si + 0x00:byte];
		si = si + 0x01;
		*siOut = si;
		if (al_18 == 0x00)
			break;
		ax = DPB(ax, al_18 - 0x30, 0);
		if (al_18 <u 0x30 || (al_18 >u 0x39 || al_18 <u 0x30))
			break;
		word16 dx_50 = dx_17 * 0x02;
		word16 bx_51;
		*bxOut = dx_50;
		*dxOut = dx_50 * 0x05 + ax;
	}
	word16 cx_27;
	*cxOut = cx_12;
	if (cx_12 < 0x00)
		*dxOut = -dx_17;
	return dx_17;
}
```

**Comment by uxmal** [comment] 2019-04-03 23:33
This seems to be fixed in the `analysis-development` branch.

**Closed by uxmal** 2019-04-03 23:33 UTC
Labels: bug
