### ISSUE TITLE
6.1.0 problem with scrollbar

### ISSUE THREAD

**Issue by dhucul** [uxmal/reko#387] opened 2016-12-29 23:27 UTC
Decompile a binary
Select a long function in the project browser
Attempt to scroll down with the scrollbar
Result: freezes

**Comment by ptomin** [comment] 2016-12-30 14:04
Could you provide binary so that we could reproduce it?
> Attempt to scroll down with the scrollbar

Which scrollbar?

**Comment by uxmal** [comment] 2016-12-30 15:28
Also,since this involves the user interface, could you specify which operating environment you are running under?

**Comment by dhucul** [comment] 2017-01-06 19:01
The scrollbar for the decompiled assembly (the second windows on the right side).  Windows 10 64x anniversary edition.

**Comment by ptomin** [comment] 2017-01-08 11:21
I can not reproduce it. 
Do you catch this bug on any binary?
Could you provide binary? If licence does not allow do it, could you generate sample binary?
P.S. @dhucul Have you closed it by mistake?

**Comment by Testato** [comment] 2017-01-08 18:41
Same here, win10-64bit:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Linear address 000636C7 is not in known segment.
   at Reko.Core.SegmentMap.MapLinearAddressToAddress(UInt64 linearAddress)
   at Reko.Gui.Windows.Controls.DisassemblyTextModel.SetPositionAsFraction(Int32 numerator, Int32 denominator)
   at Reko.Gui.Windows.Controls.TextView.vScroll_ValueChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ScrollBar.OnValueChanged(EventArgs e)
   at System.Windows.Forms.ScrollBar.set_Value(Int32 value)
   at System.Windows.Forms.ScrollBar.DoScroll(ScrollEventType type)
   at System.Windows.Forms.ScrollBar.WmReflectScroll(Message& m)
   at System.Windows.Forms.ScrollBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsDecompiler
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/WindowsDecompiler.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Reko.Gui
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Gui.DLL
----------------------------------------
Reko
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.DLL
----------------------------------------
Reko.Core
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Core.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Reko.ImageLoaders.MzExe
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.ImageLoaders.MzExe.DLL
----------------------------------------
Reko.Arch.X86
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Arch.X86.DLL
----------------------------------------
Reko.Environments.Msdos
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Environments.Msdos.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Reko.Arch.X86.Design
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Arch.X86.Design.DLL
----------------------------------------
Reko.Environments.Msdos.Design
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/jklSoft/Reko/Reko.Environments.Msdos.Design.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by ptomin** [comment] 2017-01-08 19:07
@Testato Good log. Will try to fix it.
Which scrollbar do you click? It seems to disassembly (bottom) window at Memory View tab, is not it?

**Comment by Testato** [comment] 2017-01-08 20:40
Yes, disassembly scrollbar.
It is random, you need pull up/down fast by mouse for trig the bug.

**Comment by ptomin** [comment] 2017-01-09 14:02
52646d1 should fix it.
@Testato  @dhucul could you check if error has gone away

**Comment by Testato** [comment] 2017-01-11 12:42
may you release a new/temporary windows gui, so i can test it ?
sorry if i go OT: i have a dos .exe, pippo.exe, and it use an externat file text.scp, for show some info inside the program.
The file text.scp is not a plaintexs file, maybe it is a binary or an encripted file, i do not know, but i cannot open only the file by Reko.
The question is: this text.scp file is automatically loaded inside REko when i open pippo.exe in reko ? Or I must manually add it to reko ? 
I tried the option "add binary" in the Reko gui, but i cannot select it.

Thanks and sorry for the OT

**Comment by uxmal** [comment] 2017-01-11 15:42
@Testato: I will make a new release in a few hours. 

There is no tutorial for Reko. What do you want to learn? :-) Feel free to ask in the gitter forum https://gitter.im/uxmal/reko

**Comment by Testato** [comment] 2017-01-11 18:31
@ptomin 
I discovered that .scp is an Atari Spartados Compressed Disk Image.
If I decompress it to .atr, probably i can "play" this program by Atari emulator.

So probably i do not need the .exe, but only this atari executable.
May Reko decompile it ? (Atari was a 68k cpu)

**Comment by Testato** [comment] 2017-01-11 23:25
I do not know witch file format is .scp file. But it is sure that .exe pull the text that I need from it.
Is it possible add it to the .exe decompilation process ?

**Comment by uxmal** [comment] 2017-01-12 08:46
Unpacking SCP files may be possible using the code in this project:
https://github.com/jduerstock/adir
Once you've done that, you can look inside the SCP file and extract files, which if executable can be decompiled with Reko.

**Comment by Testato** [comment] 2017-01-12 11:26
Thanks i will try that.

For the issue of crollbar instead, it is not solved here by version 6.2.0
The error will not trig now, but the scroll is blocked. I start to scroll, and after some millimeters of scrollbar the code inside the window is blocked. you cannot go up or down.

**Comment by ptomin** [comment] 2017-01-15 18:59
@Testato Did you reproduce it on `msdos` x86 binary?
Did whole application hang? Or just code in disassembly window was not changed when scroll bar was moved.

**Comment by uxmal** [comment] 2017-12-20 01:21
Closing for lack of response. I trust that you got it working fine, @ptomin.

**Closed by uxmal** 2017-12-20 01:21 UTC
