### ISSUE TITLE
Edit Signature menu error

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#144] opened 2016-02-05 08:07 UTC
Cannot open window of **Edit Signature** editing for M68k ROM.

**Comment by uxmal** [comment] 2016-02-05 09:24
Is this the same binary as in #122?

**Comment by lab313ru** [comment] 2016-02-05 09:29
I think, you may use any m68k binary to get this error.

**Comment by uxmal** [comment] 2016-02-05 10:38
The cause of the crash is that the `Platform` being used, the default one, has no way of serializing procedures signatures. The reason for this is that the calling conventions could vary wildly between different x86 platforms. 

What should happen here is that `Platform.CreateProcedureSerializer` may need to change to `bool TryCreateProcedureSerializer(out serializer)` and then logic needs to be changed to allow for the inability to serialize / deserialize procedure signatures.

Obviously, if you have a known platform like the Sega Genesis, it should provide a ProcedureSerializer. Do you have documentation available for how the calling convention is on that platform? I.e. how parameters are passed to a function and what registers are expected to return values? Registers preserved at every call?

**Comment by lab313ru** [comment] 2016-02-05 10:45
Whell...
There are no standard calling conventions in m68k. You are able to pass parameters via all registers d0-d7, a0-a6, or via stack. And only you are responsible for clearing stack, or preserving registers.

**Comment by uxmal** [comment] 2016-02-05 10:59
Understood, the situation is similar on x86. However, many **platforms** define calling conventions, sometimes several. For instance, on Windows there are the `__cdecl`, `__stdcall`, `__fastcall`, and `__thiscall` conventions. Does the Genesis define such a convention? I'm guessing no since it is a low-level console platform, but if there are conventions defined for it, I'd like to see them.

If there is no calling convention, it's really hard to edit signatures with the "Edit Signature" function as there is no way to automatically translate ```int strcmp(char *,char *)```into machine language without detailing how parameters are being passed to and from the procedure.

@nemerle was kind enough to augment the Reko C parser to accept `[[ ]]` attributes. In the example above, you could specify the signature of a function like this:
```
[[reko:reg:d0]] int [[reko:adjust:8]] strcmp([[reko:stack:4]]char *, [[reko:stack:8]]char *) 
```
which says "strcmp returns its value in register `d0`, takes its parameters at stack offsets 4 and 8 respectively, and after the call returns adjusts the call stack by 8 bytes". This is not fully implemented yet, but let me know if this is something you would find useful and I will put it on the enhancement list. (it's a shame github doesn't have a voting system for prioritizing issues)

**Comment by lab313ru** [comment] 2016-02-05 11:36
For example, open this raw m68k code: [unpacker.zip](https://github.com/uxmal/reko/files/119014/unpacker.zip) and you will see, that there is no registers preservation in this subroutine, and only two registers (a0, a1) are used reading from start.

It would be great to specify such things manually. Because m68k doesn't have any standard calling conventions, because you're writing pure assembler code.
Sure, there are few compilers from C code, and I don't sure about calling convention that they use.

**Comment by lab313ru** [comment] 2016-02-09 11:16
Up (sorry, because without no answers).

**Comment by uxmal** [comment] 2016-02-09 11:56
@lab313ru: I am tracking this, however #135 takes priority. I'll comment there with a progress update.

**Comment by uxmal** [comment] 2017-12-20 01:55
Dusting this off @lab313ru. It's been a while since we looked at this, but the [[reko::... ]] syntax for input and output registers has been implemented for a while. I'm closing this right now. If you find _specific_ issues with the register syntax, please do open a new issue.

**Closed by uxmal** 2017-12-20 01:55 UTC
