### ISSUE TITLE
msdos game fails to decompile

### ISSUE THREAD

**Issue by Deltrego** [uxmal/reko#237] opened 2016-05-10 11:33 UTC
Hello, I tried reko 0.6.0.0 on a 1988 dos game called Star Goose, that can be found here: http://www.myabandonware.com/game/star-goose-ix#download
It gave several errors.

Please consider adding it to the executables you use to test the decompiler.
Thank you!

**Comment by uxmal** [comment] 2016-05-10 11:46
Thanks for this issue report. I will look into it presently.

**Comment by uxmal** [comment] 2016-05-13 12:56
Status: still working on this. This executable uncovered subtle bugs in Reko's type inference. I'm off for the weekend but will continue next week.

**Comment by uxmal** [comment] 2016-05-25 07:51
Status: reko gets a lot further now, but stumbles on the goal line. A few type inferences are not succeeding. It manages to scan about 70% of the image without user intervention.

**Comment by uxmal** [comment] 2016-05-29 08:13
@Deltrego:  I've corrected the "low-hanging fruit" errors, but the remaining errors are known (see #90), and require larger changes to the codebase. These are happening in the `scanner-development` branch. Thanks for your patience!

**Comment by Deltrego** [comment] 2016-06-01 06:36
Nice to hear! You are really dedicated.
Do you already use a set of existing dos programs to test reko (like, say, qbasic.exe)? If not, maybe you could script them to automatically decompile and diff the output for discrepancies/regressions.

**Comment by uxmal** [comment] 2016-06-01 06:55
I do have a set of DOS programs that I either had in my possession, or that other Reko users have contributed. I use them in a suite to keep an eye on regressions and to discover interesting assembly language patterns that might benefit from specific targeting by the Reko. I'm unable to make this collection public for the usual reasons, but I'm always grateful for new samples.

In the light of my comment above regarding #90, I'm about to close this issue. Remember that you can circumvent a lot of the error messages caused by #90 by indicating manually where some functions start to Reko using the "Mark as procedure" command.

**Closed** 2016-06-01 10:25 UTC
